/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTableauRouteImport } from './routes/_authenticated.tableau'
import { Route as AuthenticatedRelancesRouteImport } from './routes/_authenticated.relances'
import { Route as AuthenticatedProspectsRouteImport } from './routes/_authenticated.prospects'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated.pipeline'
import { Route as AuthenticatedMailsRouteImport } from './routes/_authenticated.mails'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated.logs'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated.equipe'
import { Route as AuthenticatedProspectsIdRouteImport } from './routes/_authenticated.prospects.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTableauRoute = AuthenticatedTableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelancesRoute = AuthenticatedRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectsRoute = AuthenticatedProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMailsRoute = AuthenticatedMailsRouteImport.update({
  id: '/mails',
  path: '/mails',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectsIdRoute =
  AuthenticatedProspectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProspectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/mails': typeof AuthenticatedMailsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/prospects': typeof AuthenticatedProspectsRouteWithChildren
  '/relances': typeof AuthenticatedRelancesRoute
  '/tableau': typeof AuthenticatedTableauRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/mails': typeof AuthenticatedMailsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/prospects': typeof AuthenticatedProspectsRouteWithChildren
  '/relances': typeof AuthenticatedRelancesRoute
  '/tableau': typeof AuthenticatedTableauRoute
  '/': typeof AuthenticatedIndexRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/mails': typeof AuthenticatedMailsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/prospects': typeof AuthenticatedProspectsRouteWithChildren
  '/_authenticated/relances': typeof AuthenticatedRelancesRoute
  '/_authenticated/tableau': typeof AuthenticatedTableauRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/prospects/$id': typeof AuthenticatedProspectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/equipe'
    | '/logs'
    | '/mails'
    | '/pipeline'
    | '/profil'
    | '/prospects'
    | '/relances'
    | '/tableau'
    | '/prospects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/equipe'
    | '/logs'
    | '/mails'
    | '/pipeline'
    | '/profil'
    | '/prospects'
    | '/relances'
    | '/tableau'
    | '/'
    | '/prospects/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/equipe'
    | '/_authenticated/logs'
    | '/_authenticated/mails'
    | '/_authenticated/pipeline'
    | '/_authenticated/profil'
    | '/_authenticated/prospects'
    | '/_authenticated/relances'
    | '/_authenticated/tableau'
    | '/_authenticated/'
    | '/_authenticated/prospects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tableau': {
      id: '/_authenticated/tableau'
      path: '/tableau'
      fullPath: '/tableau'
      preLoaderRoute: typeof AuthenticatedTableauRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relances': {
      id: '/_authenticated/relances'
      path: '/relances'
      fullPath: '/relances'
      preLoaderRoute: typeof AuthenticatedRelancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects': {
      id: '/_authenticated/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AuthenticatedProspectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mails': {
      id: '/_authenticated/mails'
      path: '/mails'
      fullPath: '/mails'
      preLoaderRoute: typeof AuthenticatedMailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects/$id': {
      id: '/_authenticated/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof AuthenticatedProspectsIdRouteImport
      parentRoute: typeof AuthenticatedProspectsRoute
    }
  }
}

interface AuthenticatedProspectsRouteChildren {
  AuthenticatedProspectsIdRoute: typeof AuthenticatedProspectsIdRoute
}

const AuthenticatedProspectsRouteChildren: AuthenticatedProspectsRouteChildren =
  {
    AuthenticatedProspectsIdRoute: AuthenticatedProspectsIdRoute,
  }

const AuthenticatedProspectsRouteWithChildren =
  AuthenticatedProspectsRoute._addFileChildren(
    AuthenticatedProspectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMailsRoute: typeof AuthenticatedMailsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedProspectsRoute: typeof AuthenticatedProspectsRouteWithChildren
  AuthenticatedRelancesRoute: typeof AuthenticatedRelancesRoute
  AuthenticatedTableauRoute: typeof AuthenticatedTableauRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMailsRoute: AuthenticatedMailsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedProspectsRoute: AuthenticatedProspectsRouteWithChildren,
  AuthenticatedRelancesRoute: AuthenticatedRelancesRoute,
  AuthenticatedTableauRoute: AuthenticatedTableauRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
