/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthGmailCallbackRouteImport } from './routes/auth.gmail-callback'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated.workflows'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated.templates'
import { Route as AuthenticatedTableauRouteImport } from './routes/_authenticated.tableau'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated.scripts'
import { Route as AuthenticatedRelancesRouteImport } from './routes/_authenticated.relances'
import { Route as AuthenticatedProspectsRouteImport } from './routes/_authenticated.prospects'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated.pipeline'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated.logs'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedFroidsRouteImport } from './routes/_authenticated.froids'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated.equipe'
import { Route as AuthenticatedChasseRouteImport } from './routes/_authenticated.chasse'
import { Route as AuthenticatedApolloRouteImport } from './routes/_authenticated.apollo'
import { Route as AuthenticatedProspectsIdRouteImport } from './routes/_authenticated.prospects.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthGmailCallbackRoute = AuthGmailCallbackRouteImport.update({
  id: '/auth/gmail-callback',
  path: '/auth/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTableauRoute = AuthenticatedTableauRouteImport.update({
  id: '/tableau',
  path: '/tableau',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelancesRoute = AuthenticatedRelancesRouteImport.update({
  id: '/relances',
  path: '/relances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectsRoute = AuthenticatedProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFroidsRoute = AuthenticatedFroidsRouteImport.update({
  id: '/froids',
  path: '/froids',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChasseRoute = AuthenticatedChasseRouteImport.update({
  id: '/chasse',
  path: '/chasse',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApolloRoute = AuthenticatedApolloRouteImport.update({
  id: '/apollo',
  path: '/apollo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProspectsIdRoute =
  AuthenticatedProspectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedProspectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apollo': typeof AuthenticatedApolloRoute
  '/chasse': typeof AuthenticatedChasseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/froids': typeof AuthenticatedFroidsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/prospects': typeof AuthenticatedProspectsRouteWithChildren
  '/relances': typeof AuthenticatedRelancesRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tableau': typeof AuthenticatedTableauRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/apollo': typeof AuthenticatedApolloRoute
  '/chasse': typeof AuthenticatedChasseRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/froids': typeof AuthenticatedFroidsRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/prospects': typeof AuthenticatedProspectsRouteWithChildren
  '/relances': typeof AuthenticatedRelancesRoute
  '/scripts': typeof AuthenticatedScriptsRoute
  '/tableau': typeof AuthenticatedTableauRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/prospects/$id': typeof AuthenticatedProspectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/apollo': typeof AuthenticatedApolloRoute
  '/_authenticated/chasse': typeof AuthenticatedChasseRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/froids': typeof AuthenticatedFroidsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/prospects': typeof AuthenticatedProspectsRouteWithChildren
  '/_authenticated/relances': typeof AuthenticatedRelancesRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRoute
  '/_authenticated/tableau': typeof AuthenticatedTableauRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/auth/gmail-callback': typeof AuthGmailCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/prospects/$id': typeof AuthenticatedProspectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/apollo'
    | '/chasse'
    | '/equipe'
    | '/froids'
    | '/inbox'
    | '/logs'
    | '/pipeline'
    | '/profil'
    | '/prospects'
    | '/relances'
    | '/scripts'
    | '/tableau'
    | '/templates'
    | '/workflows'
    | '/auth/gmail-callback'
    | '/prospects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/apollo'
    | '/chasse'
    | '/equipe'
    | '/froids'
    | '/inbox'
    | '/logs'
    | '/pipeline'
    | '/profil'
    | '/prospects'
    | '/relances'
    | '/scripts'
    | '/tableau'
    | '/templates'
    | '/workflows'
    | '/auth/gmail-callback'
    | '/'
    | '/prospects/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/apollo'
    | '/_authenticated/chasse'
    | '/_authenticated/equipe'
    | '/_authenticated/froids'
    | '/_authenticated/inbox'
    | '/_authenticated/logs'
    | '/_authenticated/pipeline'
    | '/_authenticated/profil'
    | '/_authenticated/prospects'
    | '/_authenticated/relances'
    | '/_authenticated/scripts'
    | '/_authenticated/tableau'
    | '/_authenticated/templates'
    | '/_authenticated/workflows'
    | '/auth/gmail-callback'
    | '/_authenticated/'
    | '/_authenticated/prospects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthGmailCallbackRoute: typeof AuthGmailCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/gmail-callback': {
      id: '/auth/gmail-callback'
      path: '/auth/gmail-callback'
      fullPath: '/auth/gmail-callback'
      preLoaderRoute: typeof AuthGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tableau': {
      id: '/_authenticated/tableau'
      path: '/tableau'
      fullPath: '/tableau'
      preLoaderRoute: typeof AuthenticatedTableauRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relances': {
      id: '/_authenticated/relances'
      path: '/relances'
      fullPath: '/relances'
      preLoaderRoute: typeof AuthenticatedRelancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects': {
      id: '/_authenticated/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof AuthenticatedProspectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/froids': {
      id: '/_authenticated/froids'
      path: '/froids'
      fullPath: '/froids'
      preLoaderRoute: typeof AuthenticatedFroidsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chasse': {
      id: '/_authenticated/chasse'
      path: '/chasse'
      fullPath: '/chasse'
      preLoaderRoute: typeof AuthenticatedChasseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apollo': {
      id: '/_authenticated/apollo'
      path: '/apollo'
      fullPath: '/apollo'
      preLoaderRoute: typeof AuthenticatedApolloRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prospects/$id': {
      id: '/_authenticated/prospects/$id'
      path: '/$id'
      fullPath: '/prospects/$id'
      preLoaderRoute: typeof AuthenticatedProspectsIdRouteImport
      parentRoute: typeof AuthenticatedProspectsRoute
    }
  }
}

interface AuthenticatedProspectsRouteChildren {
  AuthenticatedProspectsIdRoute: typeof AuthenticatedProspectsIdRoute
}

const AuthenticatedProspectsRouteChildren: AuthenticatedProspectsRouteChildren =
  {
    AuthenticatedProspectsIdRoute: AuthenticatedProspectsIdRoute,
  }

const AuthenticatedProspectsRouteWithChildren =
  AuthenticatedProspectsRoute._addFileChildren(
    AuthenticatedProspectsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApolloRoute: typeof AuthenticatedApolloRoute
  AuthenticatedChasseRoute: typeof AuthenticatedChasseRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFroidsRoute: typeof AuthenticatedFroidsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedProspectsRoute: typeof AuthenticatedProspectsRouteWithChildren
  AuthenticatedRelancesRoute: typeof AuthenticatedRelancesRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRoute
  AuthenticatedTableauRoute: typeof AuthenticatedTableauRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApolloRoute: AuthenticatedApolloRoute,
  AuthenticatedChasseRoute: AuthenticatedChasseRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFroidsRoute: AuthenticatedFroidsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedProspectsRoute: AuthenticatedProspectsRouteWithChildren,
  AuthenticatedRelancesRoute: AuthenticatedRelancesRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRoute,
  AuthenticatedTableauRoute: AuthenticatedTableauRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthGmailCallbackRoute: AuthGmailCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
